include(ProcessorCount)

ProcessorCount(PARALLELISM)
if(PARALLELISM EQUAL 0)
  set(PARALLELISM 1)
endif()

message(
  STATUS
    "Setting CMAKE_BUILD_PARALLEL_LEVEL and CTEST_PARALLEL_LEVEL to ${PARALLELISM}"
)
file(
  APPEND "$ENV{GITHUB_ENV}"
  "CMAKE_BUILD_PARALLEL_LEVEL=${PARALLELISM}\n"
  "CTEST_PARALLEL_LEVEL=${PARALLELISM}\n"
)